name: Build Reader Image  

on:
    release:
        types: [published]

jobs:
  job1:
    name: Build-Openjdk-8
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/reader

      - name: Set Version
        id: set-version
        run: |
          version=$(echo "${GITHUB_REF:10}" | cut -d'-' -f1 | sed 's/^v//')
          echo "ReleaseTag=${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-Openjdk-8
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v6
            linux/arm/v7
            linux/386
            linux/ppc64le
            linux/s390x
          push: true
          build-args: |
            READER_TAG=${{ steps.set-version.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reader:${{ steps.set-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/reader:latest
          labels: ${{ steps.meta.outputs.labels }}

  job2:
    name: Build-Openj9
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/reader

      - name: Set Version
        id: set-version
        run: |
          version=$(echo "${GITHUB_REF:10}" | cut -d'-' -f1 | sed 's/^v//')
          echo "ReleaseTag=${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-Openj9
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Openj9.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: |
            READER_TAG=${{ steps.set-version.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reader:openj9-${{ steps.set-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/reader:openj9-latest
          labels: ${{ steps.meta.outputs.labels }}

  job3:
    needs: [job1, job2]
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/reader
          short-description: 支持PUID，PGID，Umask设置的Reader镜像
          readme-filepath: ./README.md
